version: '2'
services:
  gbccvbank-app:
    image: gbccvbank
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gbccvbank-postgresql:5432/GBCCVBank
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  gbccvbank-postgresql:
    extends:
      file: postgresql.yml
      service: gbccvbank-postgresql
